name: Forked Build Workflow
on:
  workflow_dispatch:
  pull_request:
  release:
    types:
      - published

permissions:
  contents: write
  packages: write

jobs:
  go:
    uses: ./.github/workflows/go-releaser.yml
    with:
      go-version: '1.22'
  docker:
    needs: go
    uses: ./.github/workflows/docker-build-and-push.yml
